### ISSUE TITLE
Maquetado móvil

### ISSUE THREAD

**Issue by Breitner12** [CarsOk/ADSO2558427EQUIPO2MOVIL#11]
Yo como: team scrum.
Quiero: crear un maquetado del app móvil.
Para: visualizar de una mejor forma el diseño del aplicativo móvil.

##Criterios de aceptación:
[] tener una visualización de como va a quedar el diseño.
[] investigar como diseñar un app móvil.

**Comment by GoJhon** [comment]
Esta historia de usuario se cierra por una modificación urgente del spreen 2.
